server {
    listen 9000;
    server_name localhost;

    # Set the root directory where the front-end files are located
    root /var/www/html/softy-pinko-front-end;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

